const fs = require('fs');
const h = fs.readFileSync('C:/Users/euler/MudaBrasil/pages/meu-voto.html', 'utf8');
const ids = [];
h.replace(/id="([^"]+)"/g, (m, g) => { ids.push(g); return m; });
const js = fs.readFileSync('C:/Users/euler/MudaBrasil/js/thermometer.js', 'utf8');
const need = new Set();
js.replace(/\$\('([^']+)'\)/g, (m, g) => { need.add(g); return m; });
const missing = [...need].filter(id => !ids.includes(id));
console.log('FALTANDO no meu-voto.html:', missing.join(', ') || '(nenhum)');
console.log('total ids referenciados:', need.size);
